### PR TITLE
Made the notes section more formal :)

### PR DESCRIPTION
**Pull request by AstroOrbis**

### CODE REVIEW

**Comment by AstroOrbis** [comment]
Don’t merge this yet, I’m still working on it :p

**Comment by AstroOrbis** [comment]
Ok, you can merge now :)

**Comment by xyzzzzzzzzzzzzzz** [comment]
Love how the owners of repos like this just go inactive. Even when there's a breaking change and people offer to fix it they still don't care lol.

**Comment by AstroOrbis** [comment]
yeah, try pinging them I think

**Comment by AstroOrbis** [comment]
@ExtremeDude-tech can you merge this pls

**Pull request merged**
